import type { Metadata } from "next";
import { Inter } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';
import { NextAuthProvider } from '@/components/utils/NextAuthSessionProvider';
import { ThemeProvider } from '@/components/utils/Themeprovider';
import { TrpcProvider } from '@/components/utils/TrpcProvider';

import './globals.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <NextAuthProvider>
              {children}
              <Toaster />
            </NextAuthProvider>
          </ThemeProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
